# The URL the site will be built for
base_url = "https://blog.victorviale.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "papermod"

taxonomies = [
    { name = "tags", feed = true }
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]

[extra.papermod]
title = "Victor Viale"
default_theme = "auto"
theme = "dark"
language_direction = "ltr"
keywords = ["keyword1", "keyword2", "keyword3"]
show_theme_toggle = true
show_scroll_to_top = true
show_code_copy_buttons = true
show_reading_time = true
show_word_count = false
show_post_nav_links = true
show_post_meta = true
default_toc_open = false
edit_post_url = "https://github.com/koroeskohr/koroeskohr.github.io/tree/main"
#copyright = ""
date_format = "%Y-%m-%d"
navigation = [
    { url = "$BASE_URL/archive", title = "Archive" },
    { url = "$BASE_URL/tags", title = "Tags" }
]

home_title = "Victor Viale's blog"
home_content = ""
social_icons = [
    { url = "https://github.com/koroeskohr", title = "GitHub", icon = "github" },
    { url = "https://bsky.app/profile/koroeskohr.bsky.social", title = "BlueSky", icon = "bluesky" },
    { url = "https://twitter.com/koroeskohr", title = "Twitter", icon = "twitter" },
    { url = "$BASE_URL/atom.xml", title = "RSS", icon = "rss" },
]
